joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

controller_manager:
  ros__parameters:
    update_rate: 200
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints: [arm_base_yaw, arm_shoulder_pitch, arm_elbow_pitch, arm_wrist_pitch]
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: false
    constraints:
      goal_time: 8.0
      stopped_velocity_tolerance: 0.02
      arm_base_yaw:       {trajectory: 0.3, goal: 0.08}
      arm_shoulder_pitch: {trajectory: 0.3, goal: 0.08}
      arm_elbow_pitch:    {trajectory: 0.3, goal: 0.08}
      arm_wrist_pitch:    {trajectory: 0.3, goal: 0.08}
