<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- 센서 마스트(기둥 + RGB-D + 2D LiDAR + IMU) -->
  <!-- params:
       parent        : 붙일 부모 링크(기본: chassis)
       prefix        : 프레임/센서 이름 접두사(기본: mast)
       x y z         : parent 기준 마스트 하단 위치 (m)
       mast_x/y/z    : 마스트(기둥) 박스 크기 (m)
       cam_hfov      : RGB-D 수평 FOV(rad)
       cam_w/h       : 이미지 해상도(px)
       cam_near/far  : RGB-D 클리핑(m)
       cam_update    : RGB-D 업데이트(Hz)
       cam_topic     : RGB-D 루트 토픽 (기본: mast_camera)
       scan_update   : LiDAR 업데이트(Hz)
       scan_topic    : LiDAR 토픽 (기본: mast_scan)
       imu_update    : IMU 업데이트(Hz)
       imu_topic     : IMU 토픽 (기본: mast_imu)
  -->
  <xacro:macro name="mount_mast_sensors"
               params="parent:='chassis'
                       prefix:='mast'
                       x:=0.0 y:=0.0 z:=0.55
                       mast_x:=0.10 mast_y:=0.10 mast_z:=0.15
                       cam_hfov:=1.05 cam_w:=320 cam_h:=240
                       cam_near:=0.25 cam_far:=12.0 cam_update:=20 cam_topic:='mast_camera'
                       scan_update:=12 scan_topic:='mast_scan'
                       imu_update:=50 imu_topic:='mast_imu'">

    <!-- 0) 마스트(기둥) -->
    <joint name="${prefix}_pillar_joint" type="fixed">
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child  link="${prefix}_pillar"/>
    </joint>

    <link name="${prefix}_pillar">
      <inertial>
        <mass value="0.5"/>
        <origin xyz="0 0 ${mast_z/2.0}" rpy="0 0 0"/>
        <inertia ixx="3.0e-3" iyy="3.0e-3" izz="3.0e-3" ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${mast_z/2.0}" rpy="0 0 0"/>
        <geometry><box size="${mast_x} ${mast_y} ${mast_z}"/></geometry>
        <material name="blue"><color rgba="0.1 0.3 0.8 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 ${mast_z/2.0}" rpy="0 0 0"/>
        <geometry><box size="${mast_x} ${mast_y} ${mast_z}"/></geometry>
      </collision>
    </link>

    <!-- 1) RGB-D 카메라 (마스트 상단 바로 위, 전방 지향) -->
    <joint name="${prefix}_rgbd_joint" type="fixed">
      <origin xyz="0 0 ${mast_z}" rpy="0 0 0"/>
      <parent link="${prefix}_pillar"/>
      <child  link="${prefix}_rgbd_link"/>
    </joint>

    <link name="${prefix}_rgbd_link">
      <inertial>
        <mass value="0.15"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1.5e-4" iyy="1.5e-4" izz="1.5e-4" ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="0.10 0.04 0.04"/></geometry>
        <material name="black"><color rgba="0.1 0.1 0.1 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="0.10 0.04 0.04"/></geometry>
      </collision>
    </link>

    <!-- optical frame (z+ forward, x+ right, y+ down) -->
    <joint name="${prefix}_rgbd_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="-1.57079632679 0 -1.57079632679"/>
      <parent link="${prefix}_rgbd_link"/>
      <child  link="${prefix}_rgbd_optical"/>
    </joint>
    <link name="${prefix}_rgbd_optical"/>

    <gazebo reference="${prefix}_rgbd_link">
      <sensor name="${prefix}_rgbd_sensor" type="rgbd_camera">
        <always_on>1</always_on>
        <update_rate>${cam_update}</update_rate>
        <visualize>true</visualize>
        <topic>${cam_topic}</topic>                 <!-- 전방 카메라와 충돌 방지 -->
        <gz_frame_id>${prefix}_rgbd_link</gz_frame_id>
        <camera>
          <horizontal_fov>${cam_hfov}</horizontal_fov>
          <image><width>${cam_w}</width><height>${cam_h}</height></image>
          <clip><near>${cam_near}</near><far>${cam_far}</far></clip>
          <optical_frame_id>${prefix}_rgbd_optical</optical_frame_id>
        </camera>
      </sensor>
    </gazebo>

    <!-- 2) 2D LiDAR (카메라 위에 얹음) -->
    <joint name="${prefix}_lidar_joint" type="fixed">
      <origin xyz="0 0 ${mast_z + 0.06}" rpy="0 0 0"/>
      <parent link="${prefix}_pillar"/>
      <child  link="${prefix}_lidar_link"/>
    </joint>

    <link name="${prefix}_lidar_link">
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="5e-5" iyy="5e-5" izz="5e-5" ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="0.04" length="0.02"/></geometry>
        <material name="gray"><color rgba="0.6 0.6 0.6 1"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="0.04" length="0.02"/></geometry>
      </collision>
    </link>

    <gazebo reference="${prefix}_lidar_link">
      <sensor name="${prefix}_gpu_lidar" type="gpu_lidar">
        <always_on>1</always_on>
        <update_rate>${scan_update}</update_rate>
        <visualize>true</visualize>
        <topic>${scan_topic}</topic>
        <gz_frame_id>${prefix}_lidar_link</gz_frame_id>
        <lidar>
          <scan>
            <horizontal>
              <samples>720</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159265359</min_angle>
              <max_angle> 3.14159265359</max_angle>
            </horizontal>
          </scan>
          <range><min>0.05</min><max>10.0</max><resolution>0.01</resolution></range>
          <noise><type>gaussian</type><mean>0.0</mean><stddev>0.01</stddev></noise>
          <frame_id>${prefix}_lidar_link</frame_id>
        </lidar>
      </sensor>
    </gazebo>

    <!-- 3) IMU (맨 위 또는 마스트 중간) -->
    <joint name="${prefix}_imu_joint" type="fixed">
      <origin xyz="0 0 ${mast_z + 0.12}" rpy="0 0 0"/>
      <parent link="${prefix}_pillar"/>
      <child  link="${prefix}_imu_link"/>
    </joint>
    <link name="${prefix}_imu_link"/>

    <gazebo reference="${prefix}_imu_link">
      <sensor name="${prefix}_imu" type="imu">
        <always_on>1</always_on>
        <update_rate>${imu_update}</update_rate>
        <visualize>true</visualize>
        <topic>${imu_topic}</topic>
        <enable_metrics>true</enable_metrics>
        <gz_frame_id>${prefix}_imu_link</gz_frame_id>
      </sensor>
    </gazebo>

  </xacro:macro>

</robot>
